[tool.pytest.ini_options]
pythonpath = [
  ".", "src",
]

addopts = "--tb=short"

log_cli        = 1
log_cli_level  = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s"

log_file        = "logs/pytest/pytest.log"
log_file_level  = "DEBUG"
log_file_format = "%(asctime)s [%(levelname)8s] %(message)s"
